notifications:
  on_success: change
  on_failure: change

os: linux
language: c++
sudo: required

services:
- docker

install:
- docker build -t builder .

script:
- docker run builder /bin/cat /esp8266-firmware/firmware.bin > firmware.bin
- "strings firmware.bin | grep 'firmware: Hello!'"

deploy:
  provider: releases
  api_key:
    secure: "dw+Cf70bWu6Bo6kJxIA0y1LHa7BVYh4JlWXMg/d9s/y96s899INdiNayKN+vI6unFqUtvSUdU5mAOp7B2ctie2hmHd/7x+VXx0iMsiE8n45/i8w1yPM7SbjrAeGkxfVWqx4HbDOmCMHiMpbgjjrSrHj7Gjk3Ip/CSEdRjcPnH8Lj8qVnsJER/Ncwzg/ACncFIz5Xf+WtN2r9xTcaYzWgBHjw+xM8N1s3tcL1aoNvV2VEVToOJfNTpLrSm9OWhEjPvh08EoMMJqPHWpevslghKnc+7tCNTb+oS8VxqVPpox/4UlkzsuphRorSGcm94oRrGHeqYL30XjhRyql8dHxIJNSywxd9oBkBaxFmLoLhSR7EOWNjN39oyU1hIlCbWA1Ms2gJXvYlsArDhxyyp6odKUQK4pR1DMgpFi8u1LZBVn39T8qiYgjDWdDkkUWabt9smYT9gxe7eFRo4hKbe5E6y0v6aAz7abW34lkC7ys7zVROM8bpJMChrXtDwQJrSm3C2Mec3Ie3zLOyuVVYgCZHMWm/NnuzIsBl8wwqHDFFq6gSezeDymTBTxfuAIfIANVle2F3pIloN7xX2yFEh1bUCstSaLAJab5kcvqCJDFmELqHpKmVAh1jwaWqwBDK3DgsTecepO2sCH3YRP+pShQI654bCj41IO4qWKx4t5acwD0="
  file: firmware.bin
  skip_cleanup: true
  on:
    tags: true
