notifications:
  on_success: change
  on_failure: change

os: linux
language: c++
sudo: required

services:
- docker

install:
- docker build -t builder .

script:
- docker run builder /bin/cat /esp8266-firmware/firmware.bin > firmware.bin
- "strings firmware.bin | grep 'firmware: Hello!'"

deploy:
  provider: releases
  api_key:
    secure:  "NvFWaLaroMhkBOWDVUimpmbZWAPQjLBDXCy8ZDGA4D8eo4FraespweGfdPWuIA2aUmU/CUSEr9dezC9fukor+QwQFcSsY+auqAupbulfwk5XCdR8zSeTroyRVo33K6i5lCM5tiCkyKRzcgCkuIfAfv9ASdFK0lJM6cTAqal23k3L8IcUic9J6a73fzViqhdrg8THC9vObKqevZQVoXp6TmeNJm/vjQBqnTlERrXQqt/HdYgDjB2usLE+1Zk11s6sS3Sui9kdI9qqi2w/SYgM5ipNmKL+y/0Wk7gbToU+x/jOQr+d8N7qZq9fEdPk93DvStQTDO4z9XmyFKQbiVnjfm8JwAudkszr1fZqWfWoa3mkjAWI7pjXs23xYYI/qN6LEXepLxutpqIZjoKtttW1X1+LvMBYUnLzGu5Nj5tYp2UnLQtkeQISZED6oTPwbs0dtmCm9wqtDLPzvmC85Hc9iW3zEwZoMjg27iLbE057nfYVN7cwsFsVTxUdfbiEWeC9dbkVJ/7nrDioDnj1Ehn7nMQqitPIGkZK4AVh8hadfihoAr9ByegVkw1NyRSlZrKJSqbfxt2OhDF3w9K2V7f0eEXV/7FviAgQjylviGJcerYIgpNulUoIRa8yVljFiYk9cCWFbAqMoh7r8NfvJ29Mw1NTL09vfJ2ZifoOlgBQxg0="
  file: firmware.bin
  skip_cleanup: true
  on:
    tags: true
